### ISSUE TITLE
Question about VRAM cost

### ISSUE THREAD

**Issue by HyoKong** [CognitiveAISystems/3DGraphLLM#1]
Hi, thank you so much for the amazing project!

May I ask what the VRAM cost is for training the model? Is V100 32GB VRAM enough for training?

Thanks for the help!

**Comment by wingrune** [comment]
Hi! The VRAM usage of 3DGraphLLM depends on the size of the base LLM, the parameters of LoRA fine-tuning, the batch size, and the number of nearest neighbors. For the experiments described in the paper with knn=2 and the LLM LLAMA3-8B-Instruct, approximately 50 GB of VRAM was required with a batch size of 8. Meanwhile, conducting a basic experiment without using the scene graph (knn=0 and LLM LLAMA3-8B-Instruct) cost about 46 GB of VRAM with batch size = 8. Therefore, I’m afraid that a V100 GPU with 32GB VRAM is insufficient for training with the original training config, but there is room for reducing VRAM consumption in the method if necessary.

**Comment by HyoKong** [comment]
Thank you so much for the info!
